name: Single Integration Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integration:
    runs-on: ubuntu-latest
    env:
      AUTH_URL: http://localhost:3000
      PRODUCT_URL: http://localhost:3001
      ORDER_URL: http://localhost:3002
      GATEWAY_URL: http://localhost:3003
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build images
        run: |
          docker build -t eproject-auth ./auth
          docker build -t eproject-product ./product
          docker build -t eproject-order ./order
          docker build -t eproject-gateway ./api-gateway

      - name: Create network
        run: docker network create eproject-net || true

      - name: Start services
        run: |
          docker run -d --name mongo --network eproject-net mongo:6
          docker run -d --name rabbitmq --network eproject-net rabbitmq:3-management
          docker run -d --name auth --network eproject-net -e MONGODB_AUTH_URI=mongodb://mongo:27017/authdb -e JWT_SECRET=test_secret eproject-auth
          docker run -d --name product --network eproject-net -e MONGODB_PRODUCT_URI=mongodb://mongo:27017/productdb -e JWT_SECRET=test_secret -e AUTH_SERVICE_URL=http://auth:3000 eproject-product
          docker run -d --name order --network eproject-net -e MONGODB_ORDER_URI=mongodb://mongo:27017/orderdb eproject-order
          docker run -d --name gateway --network eproject-net -e PORT=3003 eproject-gateway

      - name: Wait for services
        run: |
          for i in $(seq 1 60); do
            (echo > /dev/tcp/localhost/3000) >/dev/null 2>&1 && (echo > /dev/tcp/localhost/3001) >/dev/null 2>&1 && (echo > /dev/tcp/localhost/27017) >/dev/null 2>&1 && break
            echo "waiting for services... ($i)"
            sleep 2
          done

      - name: Install test deps
        run: npm install --no-audit --no-fund mocha chai chai-http

      - name: Run integration test
        run: npx mocha test/integration.test.js --timeout 120000

      - name: Cleanup
        if: always()
        run: |
          docker stop auth product order gateway mongo rabbitmq || true
          docker rm auth product order gateway mongo rabbitmq || true
          docker network rm eproject-net || true
